#!/bin/bash

main()
{
    check_amount_of_arguments $@
    ensure_apl_root_variable_set
    ensure_aplunit_path_variable_set
    ensure_path_exists_and_is_writeable ${1}
    create_directory_structure $@
    create_files $@
}

check_amount_of_arguments()
{
    if [[ $# != 2 ]]
    then	
	print_usage
	exit 1
    fi
}

ensure_apl_root_variable_set() 
{
    if [[ ${APL_ROOT} == "" ]]
    then
	echo "error: APL_ROOT variable not set"
	exit 3
    fi    
}

ensure_aplunit_path_variable_set()
{
    if [[ ${APLUNIT_PATH} == "" ]]
    then
	echo "error: APLUNIT_PATH variable not set"
	exit 2
    fi
}

ensure_path_exists_and_is_writeable()
{
    if [[ ! -w ${1} ]]
    then
	echo "error: PATH not writeable"
	exit 3
    fi
}

create_directory_structure()
{
    mkdir ${1}/{src,setup,test} &> /dev/null
}

create_files()
{
    create_makefile $@
    create_setup_file $@
    create_src_and_test_files $@
}

create_makefile()
{
    MAKEFILE=${1}/Makefile
    echo '.PHONY: test' > ${MAKEFILE}
    echo 'test:' >> ${MAKEFILE}
    echo -e "\t${APL_ROOT}/mapl ${1}/setup/test_setup.dyapp" >> ${MAKEFILE}
}

create_setup_file()
{
    SETUPFILE=${1}/setup/test_setup.dyapp
    echo "Load ${APLUNIT_PATH}/UT.dyalog" > ${SETUPFILE}
    echo "Load ${1}/src/${2}.dyalog" >> ${SETUPFILE}
    echo "Run UT.run '${1}/test/${2}_tests.dyalog'" >> ${SETUPFILE}
}

create_src_and_test_files()
{
    SRC=${1}/src/${2}.dyalog
    echo ":NameSpace ${2}" > ${SRC}
    echo "" >> ${SRC}
    echo ":EndNameSpace" >> ${SRC}

    TEST=${1}/test/${2}_tests.dyalog
    echo ":NameSpace ${2}_tests" > ${TEST}
    echo "" >> ${TEST}
    echo ":EndNameSpace" >> ${TEST}
}

print_usage()
{
    echo "usage: $0 PATH NAME"
    echo "where"
    echo " PATH is the path to where the APL project is to be created"
    echo " NAME is the APL project name"
    echo ""
    echo "this will create a starter pack under PATH that contains"
    echo " Makefile - with a phony target 'test' that executes unit tests"
    echo " setup/test_setup.dyapp - a set up file invoked by the 'test' target"
    echo " src/NAME.dyapp - a SALT script with an empty namespace NAME"
    echo " test/NAME_tests.dyalog - a SALT script with an empty namespace NAME_tests"
    echo ""
    echo "The intent is that you get a set up for TDD starting with NAME using APLUnit."
    echo "Just start adding tests and type 'make' in the root folder to execute."
    echo ""
    PATH='~/'
    NAME='tdd_kata_roman'
    echo "example: $0 ${PATH} ${NAME}"
    echo "will create"
    echo " ${PATH}/Makefile"
    echo " ${PATH}/src/"
    echo " ${PATH}/src/${NAME}.dyalog"
    echo " ${PATH}/setup/"
    echo " ${PATH}/setup/test_setup.dyalog"
    echo " ${PATH}/test/"
    echo " ${PATH}/test/${NAME}_tests.dyalog"
    echo ""
    echo "environment variables:"
    echo " APLUNIT_PATH"
    echo "    assumes that you have a copy of APLUnit somewhere on your system"
    echo "    with the environment variable APLUNIT_PATH set to the root folder of APLUnit."
    echo ""
    echo " APL_ROOT "
    echo "    assumes that APL_ROOT points at the root APL directory of mapl"
}

main $@
